apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
resources: []
patchesStrategicMerge:
  - deployment_patch.yaml
images:
  - name: kong
    newName: REPLACE_WITH_IMAGE
    newTag: REPLACE_WITH_TAG
