apiVersion: v2
name: user-service
description: Helm chart for the User Service (FastAPI)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - user-service
  - jwt
maintainers:
  - name: devops
    email: devops@example.com
