apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DATABASE_TYPE: {{ .Values.env.databaseType | quote }}
  DB_PATH: {{ .Values.env.dbPath | quote }}
