apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey | b64enc | quote }}
