{{- if or (and (hasKey .Values "secrets") .Values.secrets.enabled) .Values.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ include "user-service.namespace" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ default .Values.secretKey .Values.secrets.secretKey | quote }}
{{- end }}
