apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  DB_PATH: {{ .Values.env.DB_PATH | quote }}
